### PR TITLE
[BUGFIX] Preserve important image attributes on initialization

### LINKED ISSUE #173: Title, style attributes are lost when content is modified - height and width attributes are modified
Using rte_ckeditor_image 10.2.1 with TYPO3 10.4.21, when images are inserted in news and then are modified, the title attribute is lost. If a style attribute was added with the editor, e.g. float: right to have the image at the RHS of the text, it is also lost. The height and width attribute are modified.

### PR DESCRIPTION
**Pull request by thommyhh**
Backport og #177 for v10 branch.

Fixes #173

### CODE REVIEW

**Comment by thommyhh** [comment]
@CybotTM I don't have a v10 to test this, so maybe @YolfTypo3 could test this. I applied the same changes as in #177.

**Comment by YolfTypo3** [comment]
Hi,
I tested the patch with TYPO3 10.4. Everything is OK except the style attribute which is still lost. Please add "style" in the allowedAttribites line 234 to fix this part of the bug.

**Comment by thommyhh** [comment]
@YolfTypo3 Thanks, for your feedback, I must've missed that. Please try with the updated branch again.

**Comment by YolfTypo3** [comment]
Thank you for the update. It is working fine with TYPO3 10.4.

**Pull request merged**
