### PR TITLE
Dev typo3 10.x

### PR DESCRIPTION
**Pull request by prdt3e**
Dev typo3 10.x

### CODE REVIEW

**Comment by prdt3e** [comment]
https://github.com/nhovratov/t3x-rte_ckeditor_image/tree/dev-TYPO3_10.x

Fix extensionscanner and cleanup code

**Comment by zelcode** [comment]
Hi,

you can add this if it is OK.

https://github.com/netresearch/t3x-rte_ckeditor_image/issues/69#issuecomment-662996941

**Comment by mcmulman** [comment]
@prdt3e 
Thanks for your magnificent work. We'll continue on this in [netresearch:dev-TYPO3_10.x](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-TYPO3_10.x).

**Comment by prdt3e** [comment]
Do you still think of nhovratov's CleanCode?
He made adjusted namespaces...

https://github.com/nhovratov/t3x-rte_ckeditor_image/tree/dev-TYPO3_10.x

**Comment by mcmulman** [comment]
@prdt3e 
Sorry forgot about that... thanks for mentioning.
I merged it into [dev-TYPO3_10.x](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-TYPO3_10.x).

**Pull request merged**
