### PR TITLE
Compatibility cms 9

### PR DESCRIPTION
**Pull request by thommyhh**
* change dependency to CMS 9
* make backend code compatible with CMS 9
* improve JS code to make it behave correctly in different situations
* change branch alias for dev-master to `9.0.x-dev`

### CODE REVIEW

**Comment by prdt3e** [comment]
I had a fork, but this version is better.
Works very well in Chrome, IE, IE11.

Thanks for push.
Please release.

**Comment by prdt3e** [comment]
Have you emptied the cache after updating the extension or reinstalled the extension?
Exactly this bug occurred before we reprogrammed the Resources/Public/JavaScript/Plugins/typo3image.js.

**Comment by szykuc** [comment]
Yep, even now i clear all cache from backend and manually on server and still the same error

**Comment by thommyhh** [comment]
@szykuc How to you access the editor? Which view have you opened (content element or a special module, in the normal backend view or a single frame)?

**Comment by prdt3e** [comment]
@thommyhh 
Do you get a version that runs in both (8/9) Typo3 versions?
To change the current version to 9 would be too early.

**Comment by thommyhh** [comment]
@prdt3e Unfortunately it is not possible to have a version running with CMS 8 and 9 because of the internal request structure. But we plan to support and 8.x and 9.x version. We are working on some fixes.

@szykuc You are obviously not the only one, with this error. It will take some time though to figure it out, but I'm on it.

**Comment by muh-nr** [comment]
Used for branch dev-TYPO3_9.x

**Pull request closed without merging**
