### PR TITLE
[BUGFIX] Loading RTE throws PHP Runtime Deprecation Notice

### LINKED ISSUE #235: Creation of dynamic property Netresearch\RteCKEditorImage\Database\RteImagesDbHook::$pObj is deprecated
**Bug description**
PHP Runtime Deprecation Notice: Creation of dynamic property Netresearch\RteCKEditorImage\Database\RteImagesDbHook::$pObj is deprecated and throws an exception when opening something that contains an RTE in backend.

**Expected behavior**
Calling the RTE in backend should work.

**Environment**
 - TYPO3 version: 11.5.27
 - PHP version: 8.2.3
 - Extension version: 11.0.9

### PR DESCRIPTION
**Pull request by christian-fries**
Dynamic properties are deprecated as of PHP 8.2.0. Either properties have to be declared or a class has to be marked with the `#[\AllowDynamicProperties]` attribute.

Closes #235

### CODE REVIEW

**Review by IngoMueller — CHANGES_REQUESTED** [review]
thanks for this Solution. We think we need to declare also this Variable in the Hook:

`public string $transformationKey;`

what do you think?

**Comment by christian-fries** [comment]
Can you elaborate, please? I can't find any access to a property called `transformationKey` in the whole extension.

**Comment by erauchstein** [comment]
> Can you elaborate, please? I can't find any access to a property called `transformationKey` in the whole extension.

The RteImagesDbHook.php class is called in the TYPO3 core class typo3/sysext/core/Classes/Html/RteHtmlParser.php within the transformTextForPersistence function as a user-defined transformation. The TYPO3 core class creates an object of the class and tries to set the variables pObj and transformationKey in the object.

See TYPO3 Core Class https://api.typo3.org/11.5/_rte_html_parser_8php_source.html Line 237 to 239.

The RteImagesDbHook.php class currently does not allow dynamic property assignment. Thus, when assigning the variables, the PHP Runtime Deprecation Notice: "Creation of dynamic property" occurs when you try to save an RTE text in the TYPO3 backend. Tested in TYPO3 11.5.30 with Text Content Element.

**Comment by christian-fries** [comment]
Thanks for the explanation, I didn't see that property before. I updated the PR.

**Review by IngoMueller — APPROVED** [review]

**Comment by IngoMueller** [comment]
> Thanks for the explanation, I didn't see that property before. I updated the PR.

Hey Christian,

can't revoke my "Approvement". I think the declaration of the second variable must be:

public string $transformationKey;

instead of

public string transformationKey;

**Comment by IngoMueller** [comment]
@magicsunday thx for that, but we need to adjjust the second property to a variable $transformationKey instead of transformationKey

can you do this?

**Comment by IngoMueller** [comment]
you did it. Thanks again also for this.

**Pull request merged**
